language: ruby
cache: bundler
sudo: required
addons:
  apt:
    update: true 
branches:
  only:
  - master
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
deploy:
  repo: ulaval-damas/ulaval-damas.github.io
  github_token: "$GITHUB_TOKEN"
  skip-cleanup: true
  local-dir: "./_site/"
  provider: pages
  target-branch: master
