language: ruby
cache: bundler
branches:
  only:
  - master
before_install:
  - openssl aes-256-cbc -K $encrypted_d7bc0aa1d25a_key -iv $encrypted_d7bc0aa1d25a_iv
    -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
deploy:
  repo: ulaval-damas/ulaval-damas.github.io
  skip-cleanup: true
  local-dir: "./_site/"
  provider: pages
  target-branch: master
